name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: barambani
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 60
          plugin_habits_facts: yes
          plugin_habits_from: 400
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: year
          plugin_achievements: yes
          plugin_achievements_display: compact
